import os
import time

os.system('cd')
os.system('clear')
print ("\033[1;93m  <───────[ Hoş Geldin ]───────>")
time.sleep(0.5)
print ('')
print ("Bu Program Termux'da Gerekli Olan Paketleri ve Dosyaları Otamatik Yükler.")
time.sleep(1)
print ('')

print ('\033[1;93mPython Yükleniyor.')
time.sleep(0.5)
print ('')
print ('Lütfen Bekle ...')
time.sleep(0.5)
print ('')
os.system('pkg install python -y')
print ('')

print ('\033[1;93mPython2 Yükleniyor.')
time.sleep(0.5)
print ('')
print ('Lütfen Bekle ...')
time.sleep(0.5)
print ('')
os.system('pkg install python2 -y')
print ('')

print ('\033[1;93mGithub Yükleniyor.')
time.sleep(0.5)
print ('')
print ('Lütfen Bekle ...')
time.sleep(0.5)
print ('')
os.system('pkg install git -y')
print ('')

print ('\033[1;93mNano Yükleniyor.')
time.sleep(0.5)
print ('')
print ('Lütfen Bekle ...')
time.sleep(0.5)
print ('')
os.system('pkg install nano -y')
print ('')

print ('\033[1;93mCurl Yükleniyor.')
time.sleep(0.5)
print ('')
print ('Lütfen Bekle ...')
time.sleep(0.5)
print ('')
os.system('pkg install curl -y')
print ('')

os.system('python /data/data/com.termux/files/home/dosyalar.py')
